// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeS4jfggfPcSGTmu2MxRzXDFod02G6S7U',
    appId: '1:498859519121:web:d8dc09292c99ceae1ea330',
    messagingSenderId: '498859519121',
    projectId: 'imageit-c93a9',
    authDomain: 'imageit-c93a9.firebaseapp.com',
    storageBucket: 'imageit-c93a9.appspot.com',
    measurementId: 'G-XML1KW2YH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdvFGXbsMCRhGNGFAqFTrwUAnB9O2Lm48',
    appId: '1:498859519121:android:438441a821eef50a1ea330',
    messagingSenderId: '498859519121',
    projectId: 'imageit-c93a9',
    storageBucket: 'imageit-c93a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4xz9iJMLbmXF-z20eJ0dji7SIrRqHqM',
    appId: '1:498859519121:ios:d3f259053415d4d61ea330',
    messagingSenderId: '498859519121',
    projectId: 'imageit-c93a9',
    storageBucket: 'imageit-c93a9.appspot.com',
    androidClientId:
        '498859519121-rp0e784hj3miog29lli2pitkonlsbihq.apps.googleusercontent.com',
    iosClientId:
        '498859519121-4d6s443c5aj1k4etaapa02evnb5va0va.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4xz9iJMLbmXF-z20eJ0dji7SIrRqHqM',
    appId: '1:498859519121:ios:01ce2537307cf1bd1ea330',
    messagingSenderId: '498859519121',
    projectId: 'imageit-c93a9',
    storageBucket: 'imageit-c93a9.appspot.com',
    androidClientId:
        '498859519121-rp0e784hj3miog29lli2pitkonlsbihq.apps.googleusercontent.com',
    iosClientId:
        '498859519121-5rl359rbsu0v6njgijbnu5ctuv5of9v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageit.RunnerTests',
  );
}
